# Файл: backend/.air.toml

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api ./cmd/api"
bin = "./tmp/api"
full_bin = "./tmp/api"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]
log = "air.log"

[log]
time = true

[misc]
clean_on_exit = true