# Файл: frontend/Dockerfile.dev

FROM node:20-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
# Это делается отдельно, чтобы Docker мог кэшировать этот шаг
COPY package.json .
RUN npm install

# Копируем остальной код
COPY . .

# Запускаем сервер для разработки Vite, который будет доступен снаружи контейнера
CMD ["npm", "run", "dev", "--", "--host"]